# Generated by Django 4.2.11 on 2025-10-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_to_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate History',
                'verbose_name_plural': 'Exchange Rate History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NairaDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Deposit amount in Naira', max_digits=15)),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Bitcoin amount received', max_digits=20)),
                ('exchange_rate', models.DecimalField(decimal_places=2, help_text='Exchange rate used', max_digits=15)),
                ('payment_method', models.CharField(help_text='Payment method (bank_transfer, card, etc.)', max_length=50)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment reference', max_length=100)),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Provider transaction ID', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naira_deposits', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Naira Deposit',
                'verbose_name_plural': 'Naira Deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_reference', models.CharField(help_text='Customer reference (phone, account number, etc.)', max_length=100)),
                ('bill_reference', models.CharField(help_text='Bill reference number', max_length=100)),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Bill amount in Naira', max_digits=15)),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Bitcoin amount paid', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, help_text="Provider's transaction ID", max_length=100)),
                ('provider_response', models.TextField(blank=True, help_text="Provider's response data")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='core.billprovider')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payment', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
