# Generated by Django 4.2.11 on 2025-10-03 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bitcoinwallet_seed_phrase_hash_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NairaWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Bitcoin amount to withdraw', max_digits=20)),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Naira amount to receive', max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=2, help_text='Exchange rate used', max_digits=15)),
                ('bank_account_number', models.CharField(help_text='Nigerian bank account number', max_length=20)),
                ('bank_name', models.CharField(help_text='Bank name', max_length=100)),
                ('account_name', models.CharField(help_text='Account holder name', max_length=100)),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Provider transaction ID', max_length=100)),
                ('provider_response', models.TextField(blank=True, help_text='Provider response')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naira_withdrawals', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Naira Withdrawal',
                'verbose_name_plural': 'Naira Withdrawals',
                'ordering': ['-created_at'],
            },
        ),
    ]
