# Generated by Django 4.2.11 on 2025-10-04 04:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bitcoinwallet_seed_phrase_hash_and_more'),
        ('payments', '0002_nairawithdrawal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, help_text='Unique payment ID', unique=True)),
                ('payment_request', models.CharField(help_text='Lightning payment request (BOLT11)', max_length=1000)),
                ('payment_hash', models.CharField(blank=True, help_text='Payment hash', max_length=64)),
                ('amount_sats', models.IntegerField(help_text='Amount in satoshis')),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Amount in BTC', max_digits=20)),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Amount in Naira', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Payment description')),
                ('memo', models.CharField(blank=True, help_text='Payment memo', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Bitnob transaction ID', max_length=100)),
                ('provider_response', models.TextField(blank=True, help_text='Provider response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_payments', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Lightning Payment',
                'verbose_name_plural': 'Lightning Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LightningInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, help_text='Unique invoice ID', unique=True)),
                ('payment_request', models.CharField(help_text='Lightning payment request (BOLT11)', max_length=1000)),
                ('payment_hash', models.CharField(help_text='Payment hash', max_length=64)),
                ('amount_sats', models.IntegerField(help_text='Amount in satoshis')),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Amount in BTC', max_digits=20)),
                ('amount_ngn', models.DecimalField(decimal_places=2, help_text='Amount in Naira', max_digits=15)),
                ('description', models.TextField(blank=True, help_text='Invoice description')),
                ('memo', models.CharField(blank=True, help_text='Invoice memo', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Invoice expiration time')),
                ('provider_transaction_id', models.CharField(blank=True, help_text='Bitnob transaction ID', max_length=100)),
                ('provider_response', models.TextField(blank=True, help_text='Provider response data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lightning_invoices', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Lightning Invoice',
                'verbose_name_plural': 'Lightning Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
