# Generated by Django 4.2.11 on 2025-10-02 04:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider name (MTN, Airtel, etc.)', max_length=100)),
                ('bill_type', models.CharField(help_text='Type of bill (airtime, electricity, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('provider_code', models.CharField(help_text='Provider code for API', max_length=20)),
            ],
            options={
                'verbose_name': 'Bill Provider',
                'verbose_name_plural': 'Bill Providers',
            },
        ),
        migrations.CreateModel(
            name='BitzappUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp phone number', max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitzapp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitzapp User',
                'verbose_name_plural': 'Bitzapp Users',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_to_ngn', models.DecimalField(decimal_places=2, help_text='1 BTC to NGN rate', max_digits=15)),
                ('source', models.CharField(help_text='Rate source (bitnob, mavapay, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('bill_payment', 'Bill Payment'), ('receive', 'Receive')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_btc', models.DecimalField(decimal_places=8, help_text='Amount in Bitcoin', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('amount_ngn', models.DecimalField(blank=True, decimal_places=2, help_text='Naira equivalent amount', max_digits=15, null=True)),
                ('from_address', models.CharField(blank=True, help_text='Sender Bitcoin address', max_length=100)),
                ('to_address', models.CharField(blank=True, help_text='Recipient Bitcoin address', max_length=100)),
                ('bitcoin_tx_hash', models.CharField(blank=True, help_text='Bitcoin transaction hash', max_length=100)),
                ('bill_type', models.CharField(blank=True, help_text='Type of bill (electricity, airtime, etc.)', max_length=50)),
                ('bill_reference', models.CharField(blank=True, help_text='Bill reference number', max_length=100)),
                ('merchant_account', models.CharField(blank=True, help_text='Merchant account details', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, help_text='BTC to NGN exchange rate at time of transaction', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitcoinWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(help_text='Bitcoin address for receiving funds', max_length=100, unique=True)),
                ('private_key', models.CharField(help_text='Encrypted private key', max_length=200)),
                ('balance_btc', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), help_text='Bitcoin balance in BTC', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0E-8'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_wallet', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Bitcoin Wallet',
                'verbose_name_plural': 'Bitcoin Wallets',
            },
        ),
    ]
