# Generated by Django 4.2.11 on 2025-10-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinwallet',
            name='seed_phrase_hash',
            field=models.CharField(blank=True, help_text='Hash of seed phrase for verification (non-custodial only)', max_length=200),
        ),
        migrations.AddField(
            model_name='bitcoinwallet',
            name='wallet_type',
            field=models.CharField(choices=[('custodial', 'Custodial'), ('non_custodial', 'Non-Custodial')], default='custodial', max_length=20),
        ),
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='private_key',
            field=models.CharField(blank=True, help_text='Encrypted private key (empty for non-custodial)', max_length=200),
        ),
    ]
