# Generated by Django 4.2.11 on 2025-10-02 04:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_btc', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='core.bitcoinwallet')),
            ],
            options={
                'verbose_name': 'Wallet Balance',
                'verbose_name_plural': 'Wallet Balances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BitcoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(help_text='Bitcoin transaction hash', max_length=100, unique=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('block_height', models.IntegerField(blank=True, null=True)),
                ('fee_btc', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_details', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Bitcoin Transaction',
                'verbose_name_plural': 'Bitcoin Transactions',
            },
        ),
        migrations.CreateModel(
            name='BitcoinAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('private_key', models.CharField(help_text='Encrypted private key', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitcoin_addresses', to='core.bitzappuser')),
            ],
            options={
                'verbose_name': 'Bitcoin Address',
                'verbose_name_plural': 'Bitcoin Addresses',
            },
        ),
    ]
